/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JToggleButton;

/**
 *
 * @author agungrb
 */
public class HalamanUtama extends javax.swing.JFrame implements View {

    /**
     * Creates new form HalamanUtama
     */
    public HalamanUtama() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrasi = new javax.swing.JToggleButton();
        btnPerawatan = new javax.swing.JToggleButton();
        btnRawatJalan = new javax.swing.JToggleButton();
        btnMedRecord = new javax.swing.JToggleButton();
        btnRuangan = new javax.swing.JToggleButton();
        btnDokter = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HALAMAN UTAMA");

        btnRegistrasi.setText("REEGISTRASI POLI");

        btnPerawatan.setText("PERAWATAN");

        btnRawatJalan.setText("RAWAT JALAN");

        btnMedRecord.setText("MEDICAL RECORD");

        btnRuangan.setText("RUANGAN POLI");

        btnDokter.setText("DOKTER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPerawatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRawatJalan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMedRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrasi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPerawatan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRawatJalan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JToggleButton getBtnDokter() {
        return btnDokter;
    }

    public JToggleButton getBtnMedRecord() {
        return btnMedRecord;
    }

    public JToggleButton getBtnPerawatan() {
        return btnPerawatan;
    }

    public JToggleButton getBtnRawatJalan() {
        return btnRawatJalan;
    }

    public JToggleButton getBtnRegistrasi() {
        return btnRegistrasi;
    }

    public JToggleButton getBtnRuangan() {
        return btnRuangan;
    }


    /**
     * @param args the command line arguments
     */

    
    
    
    @Override
    public void addListener(ActionListener ae) {
        btnDokter.addActionListener(ae);
        btnMedRecord.addActionListener(ae);
        btnPerawatan.addActionListener(ae);
        btnRawatJalan.addActionListener(ae);
        btnRegistrasi.addActionListener(ae);
        btnRuangan.addActionListener(ae);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDokter;
    private javax.swing.JToggleButton btnMedRecord;
    private javax.swing.JToggleButton btnPerawatan;
    private javax.swing.JToggleButton btnRawatJalan;
    private javax.swing.JToggleButton btnRegistrasi;
    private javax.swing.JToggleButton btnRuangan;
    // End of variables declaration//GEN-END:variables
}
